## static_countries
UPDATE static_countries SET cn_short_pt='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_pt='Emirados Árabes Unidos' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_pt='Afeganistão' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_pt='Antígua e Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_pt='Anguila' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_pt='Albânia' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_pt='Arménia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_pt='Antilhas Holandesas' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_pt='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_pt='Antártida' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_pt='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_pt='Samoa Americana' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_pt='Áustria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_pt='Austrália' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_pt='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_pt='Azerbaijão' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_pt='Bósnia e Herzegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_pt='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_pt='Bangladeche' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_pt='Bélgica' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_pt='Burquina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_pt='Bulgária' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_pt='Barém' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_pt='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_pt='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_pt='Bermudas' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_pt='Brunei Darussalam' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_pt='Bolívia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_pt='Brasil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_pt='Baamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_pt='Butão' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_pt='Ilha Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_pt='Botsuana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_pt='Bielorrússia' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_pt='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_pt='Canadá' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_pt='Ilhas Cocos (Keeling)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_pt='República Democrática do Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_pt='República Centro-Africana' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_pt='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_pt='Suíça' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_pt='Costa do Marfim' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_pt='Ilhas Cook' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_pt='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_pt='Camarões' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_pt='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_pt='Colômbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_pt='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_pt='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_pt='Cabo Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_pt='Ilha de Natal' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_pt='Chipre' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_pt='República Checa' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_pt='Alemanha' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_pt='Jibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_pt='Dinamarca' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_pt='Domínica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_pt='República Dominicana' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_pt='Argélia' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_pt='Equador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_pt='Estónia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_pt='Egito' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_pt='Sara Ocidental' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_pt='Eritreia' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_pt='Espanha' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_pt='Etiópia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_pt='Finlândia' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_pt='Fiji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_pt='Ilhas Falkland' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_pt='Micronésia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_pt='Faroes' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_pt='França' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_pt='Gabão' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_pt='Reino Unido' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_pt='Granada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_pt='Geórgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_pt='Guiana Francesa' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_pt='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_pt='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_pt='Gronelândia' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_pt='Gâmbia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_pt='Guiné' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_pt='Guadelupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_pt='Guiné Equatorial' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_pt='Grécia' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_pt='Ilhas Geórgia do Sul e Sandwich do Sul' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_pt='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_pt='Guão' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_pt='Guiné-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_pt='Guiana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_pt='Hong Kong S.A.R., China' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_pt='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_pt='Croácia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_pt='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_pt='Hungria' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_pt='Indonésia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_pt='Irlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_pt='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_pt='Índia' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_pt='Território Britânico do Oceano Índico' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_pt='Iraque' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_pt='Irão' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_pt='Islândia' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_pt='Itália' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_pt='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_pt='Jordânia' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_pt='Japão' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_pt='Quénia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_pt='Quirguistão' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_pt='Cambodja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_pt='Quiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_pt='Comores' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_pt='São Cristóvão e Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_pt='Coreia do Norte' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_pt='Coreia do Sul' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_pt='Koweit' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_pt='Ilhas Caimão' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_pt='Casaquistão' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_pt='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_pt='Líbano' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_pt='Santa Lúcia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_pt='Listenstaina' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_pt='Sri Lanca' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_pt='Libéria' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_pt='Lesoto' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_pt='Lituânia' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_pt='Luxemburgo' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_pt='Letónia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_pt='Líbia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_pt='Marrocos' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_pt='Mónaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_pt='Moldávia' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_pt='Madagáscar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_pt='Ilhas Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_pt='Macedónia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_pt='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_pt='Mianmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_pt='Mongólia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_pt='Macau S.A.R., China' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_pt='Ilhas Marianas Setentrionais' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_pt='Martinica' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_pt='Mauritânia' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_pt='Monserrate' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_pt='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_pt='Maurícia' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_pt='Maldivas' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_pt='Malavi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_pt='México' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_pt='Malásia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_pt='Moçambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_pt='Namíbia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_pt='Nova Caledónia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_pt='Níger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_pt='Ilha de Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_pt='Nigéria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_pt='Nicarágua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_pt='Países Baixos' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_pt='Noruega' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_pt='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_pt='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_pt='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_pt='Nova Zelândia' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_pt='Omã' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_pt='Panamá' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_pt='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_pt='Polinésia Francesa' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_pt='Papua Nova Guiné' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_pt='Filipinas' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_pt='Paquistão' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_pt='Polónia' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_pt='São Pedro e Miquelão' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_pt='Ilhas Picárnia' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_pt='Porto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_pt='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_pt='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_pt='Paraguai' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_pt='Catar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_pt='Reunião' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_pt='Roménia' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_pt='Rússia' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_pt='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_pt='Arábia Saudita' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_pt='Ilhas Salomão' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_pt='Seicheles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_pt='Sudão' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_pt='Suécia' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_pt='Singapura' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_pt='Santa Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_pt='Eslovénia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_pt='Svalbard e Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_pt='Eslováquia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_pt='Serra Leoa' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_pt='São Marinho' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_pt='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_pt='Somália' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_pt='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_pt='São Tomé e Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_pt='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_pt='Síria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_pt='Suazilândia' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_pt='Ilhas Turcas e Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_pt='Chade' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_pt='Território das Terras Austrais e Antárticas Francesas' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_pt='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_pt='Tailândia' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_pt='Tajiquistão' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_pt='Toquelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_pt='Turquemenistão' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_pt='Tunísia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_pt='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_pt='Timor-Leste' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_pt='Turquia' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_pt='Trindade e Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_pt='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_pt='Taiuão' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_pt='Tanzânia' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_pt='Ucrânia' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_pt='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_pt='Territórios Insulares dos Estados Unidos' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_pt='Estados Unidos da América' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_pt='Uruguai' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_pt='Uzbequistão' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_pt='Estado da Cidade do Vaticano' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_pt='São Vicente e Granadinas' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_pt='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_pt='Ilhas Virgens Britânicas' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_pt='Ilhas Virgens dos Estados Unidos' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_pt='Vietname' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_pt='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_pt='Wallis e Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_pt='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_pt='Iémen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_pt='Maiote' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_pt='África do Sul' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_pt='Zâmbia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_pt='Zimbabué' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_pt='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_pt='Sérvia e Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_pt='Ilhas Aland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_pt='Ilhas Heard e McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_pt='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_pt='Sérvia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_pt='Jérsia' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_pt='Ilha de Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_pt='Ilha de Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_pt='Ilha de São Martinho' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_pt='Ilha de São Bartolomeu' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_pt='Bonaire, Santo Eustáquio e Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_pt='Curaçao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_pt='Santo Martinho' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_pt='Sudão do Sul' WHERE cn_iso_2='SS';

UPDATE static_countries SET cn_official_name_pt = cn_short_pt WHERE cn_official_name_pt='' OR cn_official_name_pt IS NULL;